'use client';

import { DateTime } from 'luxon';
import { useFormatter, useTranslations } from 'next-intl';
import { useContext, useState } from 'react';

import {
	AuctionTypeBadge,
	CategoryBadge,
	CurrencyBadge,
	EndingSoonBadge,
} from '@/components/Badge';
import { BidsTable } from '@/components/BidsTable';
import { Id } from '@/components/Id';
import {
	MyOpenAuctionResultsContext,
	MyPaginatedBidsContext,
	PaginatedBidsContext,
	PaginatedWinningBidsContext,
	SingleAuctionContext,
} from '@/contexts';
import { AuctionDetailsPageContext } from '@/pages/marketplace/auction/[auctionId]/(details)/_components/Providers';
import {
	ActionIcon,
	Anchor,
	Avatar,
	Breadcrumbs,
	Button,
	Container,
	Divider,
	Group,
	Stack,
	Text,
	Title,
	Tooltip,
} from '@mantine/core';
import {
	IconAlarm,
	IconBookmark,
	IconBuildingBank,
	IconChevronRight,
	IconClock,
	IconCoins,
	IconEye,
	IconGavel,
	IconHourglassEmpty,
	IconInfoCircle,
	IconLeaf,
	IconLicense,
	IconShare,
} from '@tabler/icons-react';

import classes from './styles.module.css';

export default function Details() {
	const t = useTranslations();
	const format = useFormatter();
	const auction = useContext(SingleAuctionContext);
	const myOpenAuctionResults = useContext(MyOpenAuctionResultsContext);
	const paginatedBids = useContext(PaginatedBidsContext);
	const winningBids = useContext(PaginatedWinningBidsContext);
	const myPaginatedBids = useContext(MyPaginatedBidsContext);
	const { openBidsDrawer } = useContext(AuctionDetailsPageContext);

	const [isDetailsExpanded, setIsDetailsExpanded] = useState(false);

	return (
		<Stack className={classes.root}>
			<Stack className={`${classes.details} ${classes.section}`}>
				<Group className={classes.row}>
					<Breadcrumbs
						separator={<IconChevronRight size={14} />}
						classNames={{
							root: classes.breadcrumbs,
							separator: classes.separator,
						}}
					>
						<Anchor href="/marketplace">Marketplace</Anchor>
						<Anchor>Industry</Anchor>
						<Anchor>Flare Gas Burning</Anchor>
					</Breadcrumbs>
					<Group className={classes.cell}>
						<ActionIcon className={classes.action} variant="outline">
							<IconBookmark size={14} />
						</ActionIcon>
						<ActionIcon className={classes.action} variant="outline">
							<IconShare size={14} />
						</ActionIcon>
					</Group>
				</Group>
				<Title className={classes.title}>Flare Gas Burning</Title>
				<Group className={classes.row}>
					<Group className={classes.cell}>
						<CategoryBadge category={'industry'} />
						<AuctionTypeBadge type={auction.data.type} />
					</Group>
					<Group className={classes.cell}>
						<EndingSoonBadge endDatetime={auction.data.endDatetime} />
					</Group>
				</Group>
				<Text className={classes.description}>
					{auction.data.description ||
						'This permit grants the owning company the right to emit a specified amount of polluting gases generated by flare gas burning. This includes gases such as carbon dioxide (CO2), methane (CH4), and other pollutants.'}
				</Text>
				<Group className={classes.row}>
					<Group className={classes.owner}>
						<Avatar
							className={classes.avatar}
							name={auction.data.owner && auction.data.owner.name}
						/>
						<Anchor
							className={classes.link}
							href={`/marketplace/firm/${auction.data.ownerId}`}
						>
							{auction.data.owner && auction.data.owner.name}
						</Anchor>
					</Group>
					<Id className={classes.id} value={auction.data.id} variant="industry" />
				</Group>
			</Stack>

			<Stack className={`${classes.properties} ${classes.section}`}>
				<Divider
					label="Details"
					classNames={{
						root: classes.divider,
						label: classes.label,
					}}
				/>
				<Stack className={classes.table}>
					<Group className={classes.row}>
						{/* <Group className={classes.cell}>
							<IconLicense size={16} className={classes.icon} />
							<Text className={classes.key}>Permits Offered</Text>
							<Text className={classes.value}>
								{format.number(auction.data.permits)} permits
							</Text>
						</Group> */}
						<Group className={classes.cell}>
							<IconHourglassEmpty size={16} className={classes.icon} />
							<Text className={classes.key}>Permit Lifespan</Text>
							<Text className={classes.value}>1 year</Text>
						</Group>
						<Group className={classes.cell}>
							<IconLeaf size={16} className={classes.icon} />
							<Text className={classes.key}>Emissions Per Permit</Text>
							<Text className={classes.value}>10,000 tCO2e</Text>
						</Group>
					</Group>
					{/* <Group className={classes.row}>
						<Group className={classes.cell}>
							<IconHourglassEmpty size={16} className={classes.icon} />
							<Text className={classes.key}>Permit Lifespan</Text>
							<Text className={classes.value}>1 year</Text>
						</Group>
						<Group className={classes.cell}>
							<IconDiamond size={16} className={classes.icon} />
							<Text className={classes.key}>Emission Quality</Text>
							<Text className={classes.value}>High Quality</Text>
						</Group>
					</Group> */}
					<Group className={classes.row}>
						<Group className={classes.cell}>
							<IconClock size={16} className={classes.icon} />
							<Text className={classes.key}>Auction Start Date</Text>
							<Text className={classes.value}>
								{DateTime.fromISO(auction.data.startDatetime).toLocaleString(
									DateTime.DATETIME_SHORT,
								)}
							</Text>
						</Group>
						<Group className={classes.cell}>
							<IconAlarm size={16} className={classes.icon} />
							<Text className={classes.key}>Auction End Date</Text>
							<Text className={classes.value}>
								{DateTime.fromISO(auction.data.endDatetime).toLocaleString(
									DateTime.DATETIME_SHORT,
								)}
							</Text>
						</Group>
					</Group>
					{!isDetailsExpanded && (
						<Button
							className={classes.subtle}
							variant="subtle"
							onClick={() => setIsDetailsExpanded(true)}
						>
							Show More
						</Button>
					)}
					{isDetailsExpanded && (
						<>
							<Group className={classes.row}>
								<Group className={classes.cell}>
									<IconEye size={16} className={classes.icon} />
									<Text className={classes.key}>Number of Views</Text>
									<Text className={classes.value}>{format.number(0)} views</Text>
								</Group>
								<Group className={classes.cell}>
									<IconBuildingBank size={16} className={classes.icon} />
									<Text className={classes.key}>Number of Bidders</Text>
									<Text className={classes.value}>
										{format.number(0)} bidders
									</Text>
								</Group>
							</Group>
							<Group className={classes.row}>
								<Group className={classes.cell}>
									<IconGavel size={16} className={classes.icon} />
									<Text className={classes.key}>Number of Bids</Text>
									<Text className={classes.value}>
										{format.number(paginatedBids.data.totalCount)} bids
									</Text>
								</Group>
								<Group className={classes.cell}>
									<IconBookmark size={16} className={classes.icon} />
									<Text className={classes.key}>Number of Bookmarks</Text>
									<Text className={classes.value}>
										{format.number(0)} bookmarks
									</Text>
								</Group>
							</Group>
							<Button
								className={classes.subtle}
								variant="subtle"
								onClick={() => setIsDetailsExpanded(false)}
							>
								Show Less
							</Button>
						</>
					)}
				</Stack>
			</Stack>

			{/* <Stack className={`${classes.permits} ${classes.section}`}>
				<Divider
					label={
						<Group className={classes.row}>
							<Text className={classes.label}>Available Permits</Text>
							<Tooltip
								position="top"
								label="How many permits have been bought and how many are still available for bidding"
							>
								<IconInfoCircle size={14} className={classes.info} />
							</Tooltip>
						</Group>
					}
					classNames={{
						root: classes.divider,
						label: classes.label,
					}}
				/>
				<Group className={classes.row}>
					<Stack className={classes.cell}>
						<Text className={classes.key}>Available</Text>
						<Group className={classes.row}>
							<Text className={classes.value}>
								{format.number(
									Math.round((available / 100) * auction.data.permits),
								)}
							</Text>
							<Text className={classes.unit}>permits</Text>
						</Group>
					</Stack>
					<Slider
						classNames={{
							root: classes.slider,
							thumb: classes.thumb,
						}}
						marks={[
							{ value: 25, label: Math.round(0.25 * auction.data.permits) },
							{ value: 50, label: Math.round(0.5 * auction.data.permits) },
							{ value: 75, label: Math.round(0.75 * auction.data.permits) },
						]}
						value={available}
					/>
					<Stack className={classes.cell}>
						<Text className={classes.key}>Bought</Text>
						<Group className={classes.row}>
							<Text className={classes.value}>
								{format.number(Math.round((bought / 100) * auction.data.permits))}
							</Text>
							<Text className={classes.unit}>permits</Text>
						</Group>
					</Stack>
				</Group>
			</Stack> */}

			{auction.data.hasJoined && (
				<Stack className={`${classes.winnings} ${classes.section}`}>
					<Divider
						label={
							<Group className={classes.row}>
								<Text className={classes.label}>Your Current Winnings</Text>
								<Tooltip
									position="top"
									label="Estimated number of permits you will win based on the current winning bids"
								>
									<IconInfoCircle size={14} className={classes.info} />
								</Tooltip>
							</Group>
						}
						classNames={{
							root: classes.divider,
							label: classes.label,
						}}
					/>
					<Group className={classes.row}>
						<Stack className={classes.cell}>
							<Container className={classes.icon}>
								<IconLicense size={16} />
							</Container>
							<Text className={classes.key}>Estimated # of Permits</Text>
							<Group className={classes.row}>
								<Text className={classes.value}>
									{format.number(
										Math.round(myOpenAuctionResults.data.permitsReserved),
									)}
								</Text>
								<Text className={classes.unit}>permits</Text>
							</Group>
						</Stack>
						<Divider orientation="vertical" className={classes.divider} />
						<Stack className={classes.cell}>
							<Container className={classes.icon}>
								<IconLeaf size={16} />
							</Container>
							<Text className={classes.key}>Estimated # of Emissions</Text>
							<Group className={classes.row}>
								<Text className={classes.value}>
									{format.number(
										// TODO: Replace with actual emissions calculation
										Math.round(
											myOpenAuctionResults.data.permitsReserved * 1000,
										),
									)}
								</Text>
								<Text className={classes.unit}>tCO2e</Text>
							</Group>
						</Stack>
						<Divider orientation="vertical" className={classes.divider} />
						<Stack className={classes.cell}>
							<Container className={classes.icon}>
								<IconCoins size={16} />
							</Container>
							<Text className={classes.key}>Estimated Final Bill</Text>
							<Group className={classes.row}>
								<CurrencyBadge />
								<Text className={classes.value}>
									{format.number(
										Math.round(myOpenAuctionResults.data.finalBill),
										'money',
									)}
								</Text>
							</Group>
						</Stack>
					</Group>
					<Button
						className={classes.subtle}
						component="a"
						href={`/marketplace/auction/${auction.data.id}/results`}
						variant="subtle"
					>
						View Full Results
					</Button>
				</Stack>
			)}

			<Stack className={`${classes.bids} ${classes.section}`}>
				<Divider
					label={
						<Group className={classes.row}>
							<Text className={classes.label}>Bids Table</Text>
							<Tooltip
								position="top"
								label="View all bids placed on this auction, including your own and the winning bids"
							>
								<IconInfoCircle size={14} className={classes.info} />
							</Tooltip>
						</Group>
					}
					classNames={{
						root: classes.divider,
						label: classes.label,
					}}
				/>
				<BidsTable
					bids={paginatedBids}
					winningBids={winningBids}
					myPaginatedBids={myPaginatedBids}
					className={classes.table}
					onViewAll={openBidsDrawer}
					hideHeader
					withViewAllButton
				/>
			</Stack>
		</Stack>
	);
}
