'use client';

import { useTranslations } from 'next-intl';
import Link from 'next/link';
import { useContext, useEffect } from 'react';

import { AuctionTypeBadge, EndingSoonBadge, SectorBadge } from '@/components/Badge';
import { Id } from '@/components/Id';
import { Switch } from '@/components/SwitchCase';
import { WithSkeleton } from '@/components/WithSkeleton';
import { SingleAuctionContext } from '@/contexts';
import { Bids } from '@/pages/marketplace/auction/[auctionId]/(details)/@details/Bids';
import { Properties } from '@/pages/marketplace/auction/[auctionId]/(details)/@details/Properties';
import { Winnings } from '@/pages/marketplace/auction/[auctionId]/(details)/@details/Winnings';
import {
	ActionIcon,
	Anchor,
	Avatar,
	Breadcrumbs,
	Group,
	Skeleton,
	Stack,
	Text,
	Title,
	UnstyledButton,
} from '@mantine/core';
import { IconBookmark, IconChevronRight, IconShare, IconSlash } from '@tabler/icons-react';

import classes from './styles.module.css';

export default function Details() {
	const t = useTranslations();
	const auction = useContext(SingleAuctionContext);

	return (
		<Stack className={classes.root}>
			<Stack className={`${classes.details} ${classes.section}`}>
				<Group className={classes.row}>
					<Switch value={auction.isLoading}>
						<Switch.True>
							<Breadcrumbs
								separator={<IconChevronRight size={14} />}
								classNames={{
									root: classes.breadcrumbs,
									separator: classes.separator,
								}}
							>
								<Skeleton width={80} height={14} visible />
								<Skeleton width={80} height={14} visible />
								<Skeleton width={80} height={14} visible />
							</Breadcrumbs>
						</Switch.True>
						<Switch.False>
							<Breadcrumbs
								separator={<IconChevronRight size={14} />}
								classNames={{
									root: classes.breadcrumbs,
									separator: classes.separator,
								}}
							>
								<Anchor component={Link} href="/marketplace">
									Marketplace
								</Anchor>
								{/* TODO: change links once sectors are implemented in marketplace */}
								<Anchor component={Link} href="/marketplace">
									{t(`constants.sector.${auction.data.sector}.title`)}
								</Anchor>
								<Anchor component={Link} href="/marketplace">
									{auction.data.title.split(" - ")[0]}
								</Anchor>
							</Breadcrumbs>
						</Switch.False>
					</Switch>
					<Group className={classes.cell}>
						<ActionIcon className={classes.action} variant="outline">
							<IconBookmark size={14} />
						</ActionIcon>
						<ActionIcon className={classes.action} variant="outline">
							<IconShare size={14} />
						</ActionIcon>
					</Group>
				</Group>
				<WithSkeleton loading={auction.isLoading} width={360} height={40}>
					<Title className={classes.title}>{auction.data.title.split(" - ")[0]}</Title>
				</WithSkeleton>
				<Group className={classes.row}>
					<Group className={classes.cell}>
						<SectorBadge sector={auction.data.sector} loading={auction.isLoading} />
						<AuctionTypeBadge type={auction.data.type} loading={auction.isLoading} />
					</Group>
					<Group className={classes.cell}>
						<EndingSoonBadge auction={auction.data} />
					</Group>
				</Group>
				<Switch value={auction.isLoading}>
					<Switch.True>
						<Stack className="gap-2">
							<Skeleton height={16} visible />
							<Skeleton height={16} visible />
							<Skeleton height={16} visible />
						</Stack>
					</Switch.True>
					<Switch.False>
						<Text className={classes.description}>
							{/* TODO: use description from backend only once auction descriptions are standardized */}
							{auction.data.description ||
								'This permit grants the owning company the right to emit a specified amount of polluting gases generated by flare gas burning. This includes gases such as carbon dioxide (CO2), methane (CH4), and other pollutants.'}
						</Text>
					</Switch.False>
				</Switch>
				<Group className={classes.row}>
					<Group className={classes.owner}>
						<WithSkeleton loading={auction.isLoading} width={40} height={40} circle>
							<Avatar
								className={classes.avatar}
								name={auction.data.owner && auction.data.owner.name}
							/>
						</WithSkeleton>
						<WithSkeleton loading={auction.isLoading} width={160} height={24}>
							<Anchor
								className={classes.link}
								component={Link}
								href={`/marketplace/firm/${auction.data.ownerId}`}
							>
								{auction.data.owner && auction.data.owner.name}
							</Anchor>
						</WithSkeleton>
					</Group>
					<WithSkeleton loading={auction.isLoading} width={260} height={14}>
						<Id
							className={classes.id}
							value={auction.data.id}
							variant={auction.data.sector}
						/>
					</WithSkeleton>
				</Group>
				<Switch value={auction.isLoading}>
					<Switch.True>
						<UnstyledButton className={classes.cycle}>
							<Stack className={classes.left}>
								<Skeleton visible width={200} height={24} className="my-0.5" />
								<Skeleton visible width={240} height={14} className="my-0.5" />
							</Stack>
							<IconSlash size={28} className={classes.icon} />
							<Group className={classes.right}>
								<SectorBadge loading sector="energy" />
							</Group>
						</UnstyledButton>
					</Switch.True>
					<Switch.False>
						{auction.data.cycle && (
							<UnstyledButton
								className={classes.cycle}
								component={Link}
								href={`#`}
							>
								<Stack className={classes.left}>
									<Text className={classes.title}>
										{auction.data.cycle.title}
									</Text>
									<Text className={classes.description}>
										{auction.data.cycle.description}
									</Text>
								</Stack>
								<IconSlash size={28} className={classes.icon} />
								<Group className={classes.right}>
									{auction.data.cycle.sectors
										.sort((sector) => (auction.data.sector === sector ? 1 : -1))
										.map((sector) => (
											<SectorBadge key={sector} sector={sector} hideText />
										))}
								</Group>
							</UnstyledButton>
						)}
					</Switch.False>
				</Switch>
			</Stack>

			<Properties />
			<Winnings />
			<Bids />
		</Stack>
	);
}
