'use client';

// import { useTranslations } from 'next-intl';
import { useContext } from 'react';

import { AuctionTypeBadge, CategoryBadge, EndingSoonBadge } from '@/components/Badge';
import { Id } from '@/components/Id';
import { SingleAuctionContext } from '@/contexts';
import { Bids } from '@/pages/marketplace/auction/[auctionId]/(details)/@details/Bids';
import { Properties } from '@/pages/marketplace/auction/[auctionId]/(details)/@details/Properties';
import { Winnings } from '@/pages/marketplace/auction/[auctionId]/(details)/@details/Winnings';
import { ActionIcon, Anchor, Avatar, Breadcrumbs, Group, Stack, Text, Title } from '@mantine/core';
import { IconBookmark, IconChevronRight, IconShare } from '@tabler/icons-react';

import classes from './styles.module.css';

export default function Details() {
	// const t = useTranslations();
	const auction = useContext(SingleAuctionContext);

	return (
		<Stack className={classes.root}>
			<Stack className={`${classes.details} ${classes.section}`}>
				<Group className={classes.row}>
					<Breadcrumbs
						separator={<IconChevronRight size={14} />}
						classNames={{
							root: classes.breadcrumbs,
							separator: classes.separator,
						}}
					>
						<Anchor href="/marketplace">Marketplace</Anchor>
						<Anchor>Industry</Anchor>
						<Anchor>Flare Gas Burning</Anchor>
					</Breadcrumbs>
					<Group className={classes.cell}>
						<ActionIcon className={classes.action} variant="outline">
							<IconBookmark size={14} />
						</ActionIcon>
						<ActionIcon className={classes.action} variant="outline">
							<IconShare size={14} />
						</ActionIcon>
					</Group>
				</Group>
				<Title className={classes.title}>Flare Gas Burning</Title>
				<Group className={classes.row}>
					<Group className={classes.cell}>
						<CategoryBadge category={'industry'} />
						<AuctionTypeBadge type={auction.data.type} />
					</Group>
					<Group className={classes.cell}>
						<EndingSoonBadge auction={auction.data} />
					</Group>
				</Group>
				<Text className={classes.description}>
					{auction.data.description ||
						'This permit grants the owning company the right to emit a specified amount of polluting gases generated by flare gas burning. This includes gases such as carbon dioxide (CO2), methane (CH4), and other pollutants.'}
				</Text>
				<Group className={classes.row}>
					<Group className={classes.owner}>
						<Avatar
							className={classes.avatar}
							name={auction.data.owner && auction.data.owner.name}
						/>
						<Anchor
							className={classes.link}
							href={`/marketplace/firm/${auction.data.ownerId}`}
						>
							{auction.data.owner && auction.data.owner.name}
						</Anchor>
					</Group>
					<Id className={classes.id} value={auction.data.id} variant="industry" />
				</Group>
			</Stack>

			<Properties />
			<Winnings />
			<Bids />

			{/* <Stack className={`${classes.permits} ${classes.section}`}>
				<Divider
					label={
						<Group className={classes.row}>
							<Text className={classes.label}>Available Permits</Text>
							<Tooltip
								position="top"
								label="How many permits have been bought and how many are still available for bidding"
							>
								<IconInfoCircle size={14} className={classes.info} />
							</Tooltip>
						</Group>
					}
					classNames={{
						root: classes.divider,
						label: classes.label,
					}}
				/>
				<Group className={classes.row}>
					<Stack className={classes.cell}>
						<Text className={classes.key}>Available</Text>
						<Group className={classes.row}>
							<Text className={classes.value}>
								{format.number(
									Math.round((available / 100) * auction.data.permits),
								)}
							</Text>
							<Text className={classes.unit}>permits</Text>
						</Group>
					</Stack>
					<Slider
						classNames={{
							root: classes.slider,
							thumb: classes.thumb,
						}}
						marks={[
							{ value: 25, label: Math.round(0.25 * auction.data.permits) },
							{ value: 50, label: Math.round(0.5 * auction.data.permits) },
							{ value: 75, label: Math.round(0.75 * auction.data.permits) },
						]}
						value={available}
					/>
					<Stack className={classes.cell}>
						<Text className={classes.key}>Bought</Text>
						<Group className={classes.row}>
							<Text className={classes.value}>
								{format.number(Math.round((bought / 100) * auction.data.permits))}
							</Text>
							<Text className={classes.unit}>permits</Text>
						</Group>
					</Stack>
				</Group>
			</Stack> */}
		</Stack>
	);
}
