import Image from 'next/image';

import { CategoryBadge, CurrencyBadge } from '@/components/Badge';
import { LargeCountdown } from '@/components/Countdown';
import { getSingleAuctions } from '@/lib/auctions';
import {
	ActionIcon,
	Anchor,
	Breadcrumbs,
	Button,
	Container,
	Group,
	Stack,
	Table,
	TableTbody,
	TableTd,
	TableTh,
	TableThead,
	TableTr,
	Text,
	Title,
} from '@mantine/core';
import { IconArrowUpLeft, IconBox, IconChartLine } from '@tabler/icons-react';

interface PageProps {
	params: Promise<{ auctionId: string }>;
}
export default async function AuctionPage({ params }: PageProps) {
	const { auctionId } = await params;

	const auctionData = await getSingleAuctions(auctionId);

	return (
		<Stack>
			<Group>
				<Button leftSection={<IconArrowUpLeft />}>Previous Page</Button>
				<Breadcrumbs>
					<Anchor>Marketplace</Anchor>
					<Anchor>Industry</Anchor>
					<Anchor>Flare Gas Burning</Anchor>
				</Breadcrumbs>
			</Group>
			<Container className="relative size-80">
				<Image src={auctionData.image || '/'} alt={'Image of a power plant'} fill />
			</Container>
			<Title order={1}>Flare Gas Burning</Title>
			<CategoryBadge category={'industry'} />
			<Text>
				{auctionData.description ||
					'This permit grants the owning company the right to emit a specified amount of fluorine gases generated by air conditioning units.'}
			</Text>
			<Group>
				<IconBox />
				<Anchor href={'/marketplace/firm/bfaaf345-dd15-4ce0-ad91-6f58d1fe7a64'}>
					{auctionData.owner.name}
				</Anchor>
			</Group>
			<Group>
				<Stack>
					<Text>Number of Views</Text>
					<Text>{auctionData.views}</Text>
				</Stack>
				<Stack>
					<Text>Number of Bids</Text>
					<Text>{auctionData.bids}</Text>
				</Stack>
				<Stack>
					<Text>Number of Bookmarks</Text>
					<Text>{auctionData.bookmarks}</Text>
				</Stack>
			</Group>
			<Title order={2}>Current Winning Bids</Title>
			<Table highlightOnHover>
				<TableThead>
					<TableTr>
						<TableTh>Company</TableTh>
						<TableTh>Bid</TableTh>
						<TableTh>Permits</TableTh>
						<TableTh>Timestamp</TableTh>
						<TableTh></TableTh>
					</TableTr>
				</TableThead>
				<TableTbody>
					<TableTr>
						<TableTd>Company A</TableTd>
						<TableTd>1000</TableTd>
						<TableTd>1000</TableTd>
						<TableTd>2021-10-10 12:00:00</TableTd>
					</TableTr>
				</TableTbody>
			</Table>
			<Group>
				<Stack>
					<Text>Minimum Winning Bid</Text>
					<Group>
						<CurrencyBadge />
						<Text>1,105.99</Text>
					</Group>
					<ActionIcon>
						<IconChartLine />
					</ActionIcon>
				</Stack>
				<Stack>
					<Text>Buy Now Price</Text>
					<Group>
						<CurrencyBadge />
						<Text>1,400.00</Text>
					</Group>
				</Stack>
				<Stack>
					<Text>Ending In</Text>
					<LargeCountdown targetDate={'2028-02-07T11:44:31.000Z'} />
				</Stack>
			</Group>
			<Button>Purchase Permits</Button>
		</Stack>
	);
}
