'use client';

import Image from 'next/image';
import { useContext } from 'react';

import { AuctionTypeBadge, CategoryBadge } from '@/components/Badge';
import { Anchor, Breadcrumbs, Button, Container, Group, Stack, Text, Title } from '@mantine/core';
import { IconArrowUpLeft, IconBox } from '@tabler/icons-react';

import { AuctionDetailsContext } from '../constants';

export default function Details() {
	const { auctionData } = useContext(AuctionDetailsContext);

	return (
		<>
			<Group>
				<Button leftSection={<IconArrowUpLeft />}>Previous Page</Button>
				<Breadcrumbs>
					<Anchor>Marketplace</Anchor>
					<Anchor>Industry</Anchor>
					<Anchor>Flare Gas Burning</Anchor>
				</Breadcrumbs>
			</Group>
			<Container className="relative size-80">
				<Image src={auctionData.image || '/'} alt={'Image of a power plant'} fill />
			</Container>
			<Title order={1}>Flare Gas Burning</Title>
			<Group>
				<CategoryBadge category={'industry'} />
				<AuctionTypeBadge type={auctionData.type} />
			</Group>
			<Text>
				{auctionData.description ||
					'This permit grants the owning company the right to emit a specified amount of fluorine gases generated by air conditioning units.'}
			</Text>
			<Group>
				<IconBox />
				<Anchor href={'/marketplace/firm/bfaaf345-dd15-4ce0-ad91-6f58d1fe7a64'}>
					{auctionData.owner && auctionData.owner.name}
				</Anchor>
			</Group>
			<Group>
				<Stack>
					<Text>Permits Offered</Text>
					<Text>{auctionData.permits}</Text>
				</Stack>
				<Stack>
					<Text>Number of Views</Text>
					<Text>{auctionData.views}</Text>
				</Stack>
				<Stack>
					<Text>Number of Bids</Text>
					<Text>{auctionData.bids}</Text>
				</Stack>
				<Stack>
					<Text>Number of Bookmarks</Text>
					<Text>{auctionData.bookmarks}</Text>
				</Stack>
			</Group>
		</>
	);
}
